name: Test

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: [3.8, 3.9]

        steps:
        -   uses: actions/checkout@v2
        -   name: Set up Python ${{ matrix.python-version }}
            uses: actions/setup-python@v2
            with:
                python-version: ${{ matrix.python-version }}

        -   name: Restore pip cache
            uses: actions/cache@v2
            with:
                path: ~/.cache/pip
                key: test-${{ runner.os }}-${{ env.pythonLocation }}-${{ hashFiles('**/pyproject.toml') }}

        -   name: Install pip dependencies
            run: |
                pip install .[test]

        -   name: Test
            run: |
                pytest -vv
